travis:
  secure:
    BINSTAR_TOKEN: BWrjh0y6zNjgxXela8zgNkrx51ykg2M++X+A1T8NVNV808jUDo2p9cda4CL8mMRYCAghvg0pvk9iwtrz7vol3J1lYNRmqOn8hSS/rBZ/aZFRIie2Ob2EGGGIaiT/LS3NspzCnxKtXJbunP8EbUmY3ug7kuuZE5NwqOF31m/b3apLSY8dSz7bTPjIJr11Kmk72hZR36KibmppEHYDCsOHTcFv4tINunYRUhd9wlF/vqMMdRmhocMahTKcxGkcbA9c4xjpXPz+7BkBnU/luDv6UxpCGPWt81u03RzXAAgB16hJ1m6G/rP/sZJ5+jDMdtA/FmA2Nslv/3kknKhjDWx5k9CmstaL6Aky1IpNnl8QjMmctcuBOptvfDiLz4+svXFhXwTtbaS1VbWNj4h5nyMzDzZrOtnN3zVpzVP/3WmJ36b7zM4QcQ3YS1lPz9j8q2AkIG+mr+6JbZMTr0WZFx9+Oxd/rypaW0ESjD6t/RyBBkYkOQ1h4gBXupuejSiDvYGqIZB9N7aCG30xBO8WQ8yEP+TXw7ceIK/krvL9BLw4TI//eMgbS1Z8JSF+s0a5ugKtvwdS2+45aYwLwR59NmpGJiZF9mvkLSc4XSD9Bki5FgScAHwEe8mIHqqq8KbqIbMFTQ3r92Y0/5SVacYFuvKVbg/d3k569n6MGGLzN+cCLLc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
