travis:
  secure:
    BINSTAR_TOKEN: MNrm9E060PofIle/hoIebzg4wHj/7yylGmWulVJ7W6F0MPJAAQTX8+DlCjd2sB+NcNh23bQwMG/wC5FekD4tvHZGEMiMRkzNDVsXlkyjLzTdg7SoXSq0mresP4A5cJo70T0DL0/SVZ/+to5dGQ76uixoLOKgfxiW00FFI1D8KpJYQz6PDByDSxXtHQZDmsoMNV0Rjm5OkWV5FzLWxP/NDMwG2GWK6aibglMSbJZPEH6CGb/1vho/as+y7o7ndxxUEO4x6OgZc3hnteqxRqNdj4xSfFIv5nuT7/P/4tXgMWS1xQIn73hTl5WIcz+pJcp+TbRxBEWvr+XYjVmUiAmiwnlXMbdkZ/IdGMgMgFrn1nQ4m7s6AcrJ4CvB2OS4LScVw6zNq44a++iDyKmA5eT5O1EVXNXgLNK1wlfzUu9VXouhkekQFa8SPlokuj+RMCTR35sMjYXpmWoenp8x7Nx5/EqLfeXFBNISEmm30PpFU9z7jLtJfb6AbFLwGViC8fJnWxuM35ZW9qIKfn2wSAEaeCulxZJFEwfpTOfH4j3WlO/1tTaokfoQ1l9clrJbK0uxYc+oSTD/2aahYD3jSL6MLXA+Pf6S8JhPAoKGy4/rJhcL+7KDbwdgVLZXiACjPBlGIFFU826eqzBWh2MdAxuoBJxH+TJ7k73ECnQWsq2fLsw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
