travis:
  secure:
    BINSTAR_TOKEN: AFr5A4w/+TtCH8nv06RHXiOIRSDEtJu931gewcCK/AD4gcDz+YZdGkLt1FIjoDamwn488Aq0j4Q2hX1M3jSIwY3pLu3Et/urcGM00hgzejvX06Y8hrXW44eu3giOPjNqLCLq45OKrbY9Iwvjze/Gum/HX3MQOhbtXU/6JdF2VDTB1okl1MMGqwOac5/jANU50TJDS0m61L5YbjnRDWKIMr7EbDaU9qngLwBosE0DCJXco0WHRTmTQEtXNditJ/P5UR3QbIYnKX+lYVXB7Nlz1ML0ki/lGAUEGQ6G1HCpd/vTr5duLSFIC0pJW902Iq0NGtliWeoMMP3ob0prOruHVk9LYbFyktGIHIb3+0F3NDqL/tMXMNIa5MHu31CDq9WpHA7sgtZIjnikcCudpnLC0+aqOwb4NN0G81TCXBfKce2WwmfAP2EP6jhO4m7TWO7GWcZ1MxgyE8FmQ3FLd6j0BCpzNfiCRSsRT3q5IMRz1DGzbWRzez28b79SZkoPs0ZrPhOJtwjR+vDY9uQD0V8fxJ0PieZ2SIFqRbmMIgvxC7ZgU1Pxlnj7vdUSrz8z2/CSvz1a2sCGb+iLYeDBW30x+VloLdxVOqkQcsLtiMqm/iS13frOcQugmcsX6xKW4hrGpMoshlt2LjKz4USHPiroyP3/yoy/s6nO/6Hwl2c1wnc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
